### ISSUE TITLE
Support for custom certificates needed

### ISSUE THREAD

**Issue by haemka** [UMEssen/FHIR-PYrate#109]
We need support for custom (self-signed) certificates or disabling certificate verification at the requests.Session. 

Something like this in [ahoy.py](https://github.com/UMEssen/FHIR-PYrate/blob/9301f22adfbf1cb9196cc7353e0acb7d3ca47ac3/fhir_pyrate/ahoy.py) should suffice:
```
def __init__(
        self,
[....]
        certbundle = True
    ) -> None:
[...]
        self.session = requests.Session()
        self.session.verify = certbundle
```

**Comment by giuliabaldini** [comment]
Hi! Thank you for the issue and for that solution! I was thinking that this might happen with other use cases, would it make sense to give an optional `requests.Session()` object as input, instead of creating it in [https://github.com/UMEssen/FHIR-PYrate/blob/9301f22adfbf1cb9196cc7353e0acb7d3ca47ac3/fhir_pyrate/ahoy.py#L57](ahoy#L57)? In such case, the user would be able to modify any parameter and then call Ahoy.

**Comment by haemka** [comment]
Since you are already creating the `requests.Session()` in Ahoy, I anticipated it would suffice to add just a certificate bundle as optional paramater.

But sure an option to inject a custom `requests.Session()` into the class would offer further opportunities for customisation. Nonetheless I would still prefer using the "standard" call (if it supports self-signed certificates), due to it's ease of use.

**Comment by giuliabaldini** [comment]
If it does not work or you still need help, just open the issue again!
